/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package games

class TicTacToe(
        val player1: Player = Player(name = "Lianne", id = 1),
        val player2: Player = Player(name = "Paul", id = 2)
) {
    private val greeting = "Welcome to the Tic Tac Toe game!"
    internal val board = Board()
    private val displayer = TextDisplayer()
    private var winner:Player? = null

    //    /// Print the updated board after every move
    fun printBoard() {
        return displayer.display(board)
    }

    //
    fun playGame() {
        val moveHistory = mutableListOf<MoveCommand>()
        println(greeting) /// greeting
        printBoard()
        var moves = 0
        val players = listOf(player1, player2)
        while(moves < 9) {
            val curPlayer = players[moves % 2]
            val validMoves = board.getValidMoves()
            try {
                val move = TextInputController().getMoveFromPlayer(curPlayer, validMoves)
                val command = MoveCommand(board, curPlayer, move)
                command.apply()
                moveHistory.add(command)
                moves++
                val winner = WinnerDetector().detectWinner(board, player1, player2)
                if (winner != null) {
                    print("${winner.name} has Won!")
                    break
                }
            } catch (u: UndoException) {
                val lastCommand = moveHistory.removeLast()
                lastCommand.undo()
                moves--
            }
            printBoard(board)
        }
    }

    fun takeTurn(p: Player, move: Move) {
        board.takeTurn(p, move)
        winner = WinnerDetector().detectWinner(board, player1, player2)
    }

    fun getWinner(): Player? {
        return winner
    }

    internal fun setState(gameState: String) {
        board.setState(gameState)
    }
}


fun main() {
    val game = TicTacToe().playGame()
}
